export type AGENT = {
  id: string;
  local_ip: string;
  public_ip: string;
  mac: string;
  computer_name: string;
  os: string;
  ram: string;
  cpu?: string;
  motherboard_serial?: string;
  hotfix?: string;
  manufacturer?: string;
  model?: string;
  network_cards?: string;
  software_info?: string;
  boot_time?: string;
  local_time?: string;
  tags?: string;
  agent_version?: string;
  agent_user?: string;
  agent_first_install?: string;
  agent_last_update?: string;
  last_seen?: string;
  created_at?: string;
};
